// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Image struct {
	ID               int64
	ImagePath        string
	OriginalFilename string
	CreatedAt        time.Time
}

type Tier struct {
	ID         int64
	Title      string
	Color      string
	TierlistID int64
	Position   float64
}

type TierImage struct {
	TierlistID int64
	TierID     int64
	ImageID    int64
	Position   float64
}

type Tierlist struct {
	ID        int64
	Title     string
	CreatedAt time.Time
}
