// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images(image_path, original_filename) VALUES(?, ?)
RETURNING id, image_path, original_filename, created_at
`

type CreateImageParams struct {
	ImagePath        string
	OriginalFilename string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.ImagePath, arg.OriginalFilename)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.ImagePath,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const createTierlist = `-- name: CreateTierlist :one
INSERT INTO tierlists(title) VALUES(?)
RETURNING id, title, created_at
`

func (q *Queries) CreateTierlist(ctx context.Context, title string) (Tierlist, error) {
	row := q.db.QueryRowContext(ctx, createTierlist, title)
	var i Tierlist
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteTierImage = `-- name: DeleteTierImage :exec
DELETE FROM tier_images
WHERE tierlist_id = ? AND image_id = ?
`

type DeleteTierImageParams struct {
	TierlistID int64
	ImageID    int64
}

func (q *Queries) DeleteTierImage(ctx context.Context, arg DeleteTierImageParams) error {
	_, err := q.db.ExecContext(ctx, deleteTierImage, arg.TierlistID, arg.ImageID)
	return err
}

const deleteTierlist = `-- name: DeleteTierlist :exec
DELETE FROM tierlists WHERE id = ?
`

func (q *Queries) DeleteTierlist(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTierlist, id)
	return err
}

const getAvailableTierlistImages = `-- name: GetAvailableTierlistImages :many
SELECT id, image_path, original_filename, created_at FROM images i
WHERE NOT EXISTS (
    SELECT 1 FROM tier_images ti
    WHERE ti.image_id = i.id AND ti.tierlist_id = ?
)
ORDER BY created_at DESC
`

func (q *Queries) GetAvailableTierlistImages(ctx context.Context, tierlistID int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableTierlistImages, tierlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ImagePath,
			&i.OriginalFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByTier = `-- name: GetImagesByTier :many
SELECT image_id, position
FROM tier_images
WHERE tierlist_id = ? AND tier_id = ?
ORDER BY position ASC
`

type GetImagesByTierParams struct {
	TierlistID int64
	TierID     int64
}

type GetImagesByTierRow struct {
	ImageID  int64
	Position float64
}

func (q *Queries) GetImagesByTier(ctx context.Context, arg GetImagesByTierParams) ([]GetImagesByTierRow, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByTier, arg.TierlistID, arg.TierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImagesByTierRow
	for rows.Next() {
		var i GetImagesByTierRow
		if err := rows.Scan(&i.ImageID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByTierlist = `-- name: GetImagesByTierlist :many
SELECT
    ti.tier_id,
    ti.position,
    i.id,
    i.image_path,
    i.original_filename
FROM tier_images ti
JOIN images i ON i.id = ti.image_id
WHERE ti.tierlist_id = ?
ORDER BY ti.position ASC
`

type GetImagesByTierlistRow struct {
	TierID           int64
	Position         float64
	ID               int64
	ImagePath        string
	OriginalFilename string
}

func (q *Queries) GetImagesByTierlist(ctx context.Context, tierlistID int64) ([]GetImagesByTierlistRow, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByTierlist, tierlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImagesByTierlistRow
	for rows.Next() {
		var i GetImagesByTierlistRow
		if err := rows.Scan(
			&i.TierID,
			&i.Position,
			&i.ID,
			&i.ImagePath,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTierlist = `-- name: GetTierlist :one
SELECT id, title, created_at FROM tierlists WHERE id = ?
`

func (q *Queries) GetTierlist(ctx context.Context, id int64) (Tierlist, error) {
	row := q.db.QueryRowContext(ctx, getTierlist, id)
	var i Tierlist
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getTiersByTierlist = `-- name: GetTiersByTierlist :many
SELECT id, title, color, position
FROM tiers
WHERE tierlist_id = ?
ORDER BY position ASC
`

type GetTiersByTierlistRow struct {
	ID       int64
	Title    string
	Color    string
	Position float64
}

func (q *Queries) GetTiersByTierlist(ctx context.Context, tierlistID int64) ([]GetTiersByTierlistRow, error) {
	rows, err := q.db.QueryContext(ctx, getTiersByTierlist, tierlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTiersByTierlistRow
	for rows.Next() {
		var i GetTiersByTierlistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Color,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
SELECT id, image_path, original_filename, created_at FROM images ORDER BY created_at DESC
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ImagePath,
			&i.OriginalFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTierlists = `-- name: ListTierlists :many
SELECT id, title, created_at FROM tierlists ORDER BY created_at
`

func (q *Queries) ListTierlists(ctx context.Context) ([]Tierlist, error) {
	rows, err := q.db.QueryContext(ctx, listTierlists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tierlist
	for rows.Next() {
		var i Tierlist
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTierImagePosition = `-- name: UpdateTierImagePosition :exec
UPDATE tier_images
SET position = ?
WHERE tierlist_id = ? AND image_id = ?
`

type UpdateTierImagePositionParams struct {
	Position   float64
	TierlistID int64
	ImageID    int64
}

func (q *Queries) UpdateTierImagePosition(ctx context.Context, arg UpdateTierImagePositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTierImagePosition, arg.Position, arg.TierlistID, arg.ImageID)
	return err
}

const updateTierlist = `-- name: UpdateTierlist :exec
UPDATE tierlists SET title = ? WHERE id = ?
`

type UpdateTierlistParams struct {
	Title string
	ID    int64
}

func (q *Queries) UpdateTierlist(ctx context.Context, arg UpdateTierlistParams) error {
	_, err := q.db.ExecContext(ctx, updateTierlist, arg.Title, arg.ID)
	return err
}

const upsertTierImage = `-- name: UpsertTierImage :exec
INSERT INTO tier_images (tierlist_id, tier_id, image_id, position)
VALUES (?, ?, ?, ?)
ON CONFLICT (image_id, tierlist_id) DO UPDATE
SET tier_id = excluded.tier_id,
    position = excluded.position
`

type UpsertTierImageParams struct {
	TierlistID int64
	TierID     int64
	ImageID    int64
	Position   float64
}

func (q *Queries) UpsertTierImage(ctx context.Context, arg UpsertTierImageParams) error {
	_, err := q.db.ExecContext(ctx, upsertTierImage,
		arg.TierlistID,
		arg.TierID,
		arg.ImageID,
		arg.Position,
	)
	return err
}
